# Generated by Django 5.1.4 on 2024-12-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogpost',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
