# Generated by Django 5.1.4 on 2024-12-30 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_api', '0002_user_alter_dogpost_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doguser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dog_api.user'),
        ),
    ]
